[package]
name = "MulticallParser"
version = "0.1.0"
edition = "2024"

[dependencies]
web3 = "0.19"
tokio = { version = "1", features = ["full"] }
alloy = { version = "0.12", features = ["full"] }
dotenv = "0.15"